
name: Get jwks

on:
  workflow_dispatch

permissions:
  id-token: write
  contents: read
  contents: write

jobs:
  get_jwks:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch GitHub OIDC Token
        id: get_jwt_gh_token
        run: |
          curl -sSL -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${{ secrets.CLIENT_ID }}" -o id-token.json
          GH_TOKEN_STR=$(jq -r '.value' id-token.json)
          KID=$(echo "$GH_TOKEN_STR" | cut -d '.' -f1 | base64 -d 2>/dev/null | jq -r .kid)
          curl -sSL https://token.actions.githubusercontent.com/.well-known/jwks -o github-jwks.json
          jq --arg KID "$KID" '{ keys: [.keys[] | select(.kid == $KID)] }' github-jwks.json > matched-jwks.json

      - name: Upload Debug Files 
        uses: actions/upload-artifact@v4
        with:
          name: oci-upst-debug
          path: |
            matched-jwks.json

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push file
        run: |
          git add matched-jwks.json
          git commit -m "Add matched-jwks.json from GitHub Actions" || echo "No changes to commit"
          git push

       



